##
# SPRING CONFIGURATION
##
spring:
  application:
    name: aplication-backend

  liquibase:
    default-schema: tesis
    change-log: classpath:db/changelog/changelog-master.xml

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tesis
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show-sql: false
        default_schema: tesis
        dialect: org.hibernate.dialect.PostgreSQL94Dialect
        use_sql_comments: true
        format_sql: true

  activemq:
    broker-url: tcp://localhost:61616
    nombre-cola : SampleQueue
    password: admin
    user: admin


